events/urls.py
from django.urls import path
from . import views


app_name="Event"


urlpatterns = [
    path('', views.event_list, name='event'),
    path('<int:pk>/', views.event_detail, name='event_detail'),
    path('create/', views.create_event, name='create'),
]

home/urls.py
from django.urls import path
from . import views


app_name="Home"


urlpatterns = [
    path('', views.index, name='home'),
]

lasu_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('news/', include('news.urls', namespace='news')),
    path('announcements/', include('announcements.urls', namespace='announcements')),
    path('events/', include('events.urls', namespace='events')),
    path('search/', include('search.urls', namespace='search')),
    path('students/', include('students.urls', namespace='student')),
    path('special_users/', include('special_users.urls')),  
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('<int:pk>/', views.news_detail, name='news_detail'),
    path('category/<int:category_id>/', views.category_news_list, name='category_news_list'),
    path('<int:news_id>/like/', views.like_news, name='like_news'),
    path('create-news/', views.create_news, name='create_news'),
    
    ]

search/urls.py
from django.urls import path
from .views import search_results

app_name = 'search'

urlpatterns = [
    path('results/', search_results, name='search_results'),
]

students/urls.py
from django.urls import path
from .views import *

app_name="student"


urlpatterns = [
    path('login/', login_view, name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('verify/', verify_matric_number, name='verify_matric_number'),
    path('register/<str:matric_number>/', register, name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LASU News - {% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/fav.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    
        
    
    

    
    
    
    {% block extra_head %}
    {% endblock %}
    {% block extra_css %}
    {% endblock %}
</head>

<body>
    {% block nav %}
    <header class="masthead mb-auto">
        <div class="navbar-bg">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-dark">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon" style="color: white;"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav mr-auto">
                                {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'news_list' %}active{% endif %}"
                                            href="{% url 'news:news_list' %}">News</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'event' %}active{% endif %}"
                                            href="{% url 'Event:event' %}">Events</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'announcements' %}active{% endif %}"
                                            href="{% url 'Announcements:announcements' %}">Announcements</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'apply_creator' %}active{% endif %}"
                                            href="{% url 'special_users:apply_creator' %}">Become a creator</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
                                            aria-current="page" href="{% url 'Home:home' %}">Home</a>
                                    </li>
                                {% endif %}
                            </ul>
    
                            {% if user.is_authenticated %}
                            <form class="form-inline my-2 my-lg-0 mx-auto" style="width: 50%;" method="GET" action="{% url 'search:search_results' %}">
                                <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" required>
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>
                            {% endif %}
    
                            <ul class="navbar-nav ml-auto">
                                {% if user.is_authenticated %}
                                    {% if user.is_special_user %}
                                        <!-- Notification Icon -->
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'notifications:notifications_list' %}">
                                                <i class="fas fa-bell fa-2x"></i>
                                                {% if unseen_notifications_count %}
                                                    <span class="badge badge-danger">{{ unseen_notifications_count }}</span>
                                                {% endif %}
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-user-circle fa-2x"></i> {{ user.username }}
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item {% if request.resolver_match.url_name == 'profile' %}active{% endif %}"
                                                href="{% url 'student:profile' %}">Profile</a>
                                            <a class="dropdown-item {% if request.resolver_match.url_name == 'logout' %}active{% endif %}"
                                                style="color: red;" href="{% url 'student:logout' %}">Logout</a>
                                        </div>
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                                            href="{% url 'student:login' %}">Sign in</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link {% if request.resolver_match.url_name == 'verify_matric_number' %}active{% endif %}"
                                            href="{% url 'student:verify_matric_number' %}">Join</a>
                                    </li>
                                {% endif %}
                            </ul>
                            
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    {% endblock %}
    


</body>

    {% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}


    <footer class="footer py-3 bg-dark text-white">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center">
                    <p>&copy; {% now "Y" %} LASU News. All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>
    
    
</body>
</html>